meta_product_name: "Creatr"
meta_title: "Creatr — Create your network"
meta_description: "Match with the professionals according to your skills and goals"
meta_image: "social.png"                       # should exist in `app/assets/images/`
